fix(preview): preview fails when `qr-target` set to "dev-build"
The qrTarget defensive check does not include the documented (and recommended) `'dev-build'` value, so the action fails with:

__Error: Invalid QR code target: "dev-build", expected "expo-go" or "dev-build"__